### ISSUE TITLE
LLVM: plans to update the repository

### ISSUE THREAD

**Issue by realqhc** [openhwgroup/corev-llvm-project#19]
I'm from PLCT Lab and am currently trying to port a patch regarding RISC-V Zce extension support onto the repo, but found that this repository is quite outdated compared to upstream. Are there any plans to merge some of the changes?

**Comment by jeremybennett** [comment]
We don't have an active project manager for this project at the moment, so the roll forward's are not as frequent as I would like. I'd encourage you to get involved.  By coincidence, the next meeting is in two hours time (15:00 UTC). Details in the calendar at the bottom of this page: https://www.openhwgroup.org/working-groups/

**Comment by CharKeaney** [comment]
In the time since this issue was raised the repository has been rolled forward. I would suggest closing the issue. You can always open another issue for this if you encounter the same issue again.

**Comment by jeremybennett** [comment]
Marking as closed on the recommendation of the project lead.
