### ISSUE TITLE
Update references to `xcorev` in CORE-V march strings with references to `xcv`

### ISSUE THREAD

**Issue by CharKeaney** [openhwgroup/corev-llvm-project#29]
Recently the decision was made to shorten `xcorev` as it appears in march strings to `xcv`. Despite this, the compiler still expects the former. This must be resolved. This will require changes to be made both within the compiler internals and within the test cases. Any and all references to the old march strings must be changed, and that includes the feature extensions in the compiler internals. I am aware that steps are being taken to change this for simd however this will have to be done for all CORE-V march strings.

I will use simd as an example here as this change is already in progress: In general I suggest changing, for example,  `xcorevsimd` to `xcvsimd` and also changing, for example, `FeatureExtXCoreVSIMD` to `FeatureExtXcvsimd` to reflect the extension naming scheme.

**Comment by jeremybennett** [comment]
@CharKeaney This seems the right approach and should be a straightforward change.  [This](https://github.com/openhwgroup/core-v-sw/blob/master/specifications/corev-isa-extension-naming.md) is the agreed spec for extension names.

**Note.**  This specification does not include the use of `-march=...xcorev` or `-march=...xcv` as a shorthand for "all the extensions".

**Comment by jeremybennett** [comment]
Resolved in commit [1422367](https://github.com/openhwgroup/corev-llvm-project/commit/1422367f064388e0ae65c2ea9e89081ce89d9136).
