### ISSUE TITLE
Replace the tags in CORE-V commits with `[RISCV]`

### ISSUE THREAD

**Issue by CharKeaney** [openhwgroup/corev-llvm-project#30]
Various different tags have been used in CORE-V commits. For consistency all CORE-V commits should use exactly one of the same tag and should use the same tag as would be used upstream in our circumstances. In upstream it is typical to use the `[RISCV]` tag for this purpose so I would suggest it is appropriate to use this tag instead. This change will make it easier to upstream from the COREV staging post. This change will require a history rewrite for the repository.

e.g. a commit called
`[COREV] Replace the tags in CORE-V commits with RISCV`
would be replaced by a commit called
`[RISCV] Replace the tags in CORE-V commits with RISCV`

**Comment by simonpcook** [comment]
I think as part of a rebase/prepare for upstream this makes sense, especially as there is now precedence for this style commit header for custom extensions.

**Comment by lewis-revill** [comment]
Agreed, this will most likely be what upstream requires so rewriting history now is probably a good idea.

**Comment by CharKeaney** [comment]
I have submitted a pull request [here](https://github.com/openhwgroup/corev-llvm-project/pull/31) for a branch which resolves this issue. This patch will require a rewrite so the '21 commits' attached are erroneous; the patch really only rewrites past commits and does not add any new ones. If you are wondering what the repo would look like after the change, please check the pull request. As previously mentioned, this change will require a history rewrite.

**Comment by ChunyuLiao** [comment]
To be honest, I don't see the benefit of this modification.
If we want to be consistent with upstream, then maybe not only the commits will have to be modified, but also some details in the file.
If we want to send a patch to upstream in the future, we need to organize the patch to https://reviews.llvm.org/ separately, so we can't reuse the current commit id.
Please help me to explain.

**Comment by jeremybennett** [comment]
@ChunyuLiao OpenHW Group Software policy is that patches to mirrors of upstream repositories should be consistent for upstream submission.  When we discover the repository has deviated from this, we need to correct it.

If there are more changes that are needed, then we need to do this.

**Comment by ChunyuLiao** [comment]
Yes, I understand, there is still some work to be done.
Do we try to change them all the time, or submit pr changes separately?

**Comment by CharKeaney** [comment]
> If we want to be consistent with upstream, then maybe not only the commits will have to be modified, but also some details in the file.

As far as the first argument goes, I think that this is not a rigorous one. I do not think that mistakes elsewhere would justify leaving a mistake here. I.e. just because there are other changes necessary for consistency to upstream does not justify leaving inconsistency to upstream in the project.

> If we want to send a patch to upstream in the future, we need to organize the patch to https://reviews.llvm.org/ separately, so we can't reuse the current commit id.

I am more sympathetic to this argument but I would say that just because we can't reuse the exact commit id does not mean we cannot reuse details such as commit messages when the time comes. In general we want to minimize the amount of work required for upstreaming when the time comes.

**Comment by ChunyuLiao** [comment]
Maybe I didn't make it clear, for example

https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/RISCV/RISCVFeatures.td#L462
If it is a vendor-defined extension，upstream:
HasVendorXVentanaCondOps or HasVendorXTHeadBa

But we use HasExtXCoreVAlu, perhaps it should be HasVendorXCoreVAlu.

Maybe we still have a lot of work to do.

**Comment by CharKeaney** [comment]
> Maybe I didn't make it clear, for example
> 
> https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/RISCV/RISCVFeatures.td#L462 If it is a vendor-defined extension，upstream: HasVendorXVentanaCondOps or HasVendorXTHeadBa
> 
> But we use HasExtXCoreVAlu, perhaps it should be HasVendorXCoreVAlu.
> 
> Maybe we still have a lot of work to do.

I think it would be a good idea to post a separate issue for this @ChunyuLiao. You are right that all possible inconsistencies should be looked at. This issue pertains only to this inconsistency so we are not concerned here with the others. We plan to correct all inconsistencies eventually.

**Comment by jeremybennett** [comment]
Since the history will need rewriting before upstreaming, there is little value in doing this on the existing history.
