### ISSUE TITLE
Mac  instruction error

### ISSUE THREAD

**Issue by ChunyuLiao** [openhwgroup/corev-llvm-project#38]
1. decoding conflict
Decoding Conflict:
                00...............101.....1011011
                .................101.....1011011
                .........................1011011
                ................................
        CV_MULUN 00_______________101_____1011011
        CV_MULURN 00_______________101_____1011011
Decoding Conflict:
                01...............101.....1011011
                .................101.....1011011
                .........................1011011
                ................................
        CV_MULHHUN 01_______________101_____1011011
        CV_MULHHURN 01_______________101_____1011011

2. https://github.com/openhwgroup/corev-llvm-project/actions/runs/4341096331/jobs/7580286236
testcase MC/RISCV/corev/mac-all-extensions.s  fail.

**Comment by realqhc** [comment]
It seems that the target `check-llvm-mc-riscv-corev-mac`  does not contain all testcases for corev mac extensions. I was testing the patch against this target and it passed, but it left mac-all-extensions.s unchecked.

**Comment by realqhc** [comment]
A patch is uploaded to adress this issue. I apologize for the mistake.
