### ISSUE TITLE
HWLP Behavior difference between LLVM and GCC

### ISSUE THREAD

**Issue by realqhc** [openhwgroup/corev-llvm-project#40]
Currently Hwlp would only perform bit shift when a non immediate is given like cv.starti 0, foo. However on the gcc side it performs bit shift for user input and crops it. As a result, uimml in LLVM can only be in range [0, 4094] while in GCC it can be [0, 16380] (note that everything not at multiple of 4 will be cropped in the bit shift process in gcc, and a warning is shown)

**Comment by jeremybennett** [comment]
@NandniJamnadas Would you be able to comment on this?
