### ISSUE TITLE
Verify CORE-V MC layer tests check disassembler

### ISSUE THREAD

**Issue by simonpcook** [openhwgroup/corev-llvm-project#45]
I noticed as an example that `simd-all-extensions.s` checks for the disassembly of instructions when `llvm-objdump` _doesn't_ have various extensions enabled, but not when it is enabled. I'm not sure whether its covered by other tests, but these tests probably should also check the disassembler works with the extension enabled, either by adding adding a `.arch` in the file, explicit options to `llvm-objdump` or [mapping symbols](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc#mapping-symbol) if you want to be more dynamic.

Update: It looks like pull request #35 might get rid of a lot of this, but something to review in tests before preparing upstream.

**Comment by melonedo** [comment]
It intentionally checks for what happens without `-xcvsimd`. https://github.com/openhwgroup/corev-llvm-project/blob/0f8666d688e17964d640274ffd2041c323f1f803/llvm/test/MC/RISCV/corev/simd-all-extensions.s#L1-L9

**Comment by melonedo** [comment]
To clarify, I was imitating [T-Head's tests](https://github.com/llvm/llvm-project/commit/54752f3ff6d50944f17c260a6dc47a4758a026fc#diff-43123952723887ae315286b50feb3678f2438301c684f0415f5b2fbd32f6076a) when I created these checks.
