### ISSUE TITLE
What is the version of XCV extensions implemented here?

### ISSUE THREAD

**Issue by realqhc** [openhwgroup/corev-llvm-project#69]
Currently all upstreamed LLVM work states that the version of xcv extension is 1.3.1 as it is the newest version at time of upstreaming. However, there is a slight issue with it. 

https://github.com/riscv-non-isa/riscv-toolchain-conventions/blob/master/README.mkd#list-of-vendor-extensions
In the list above it states that the version is 1.0.0, and this also reflects on recent pr in GNU toolchain https://github.com/openhwgroup/corev-binutils-gdb/commit/9b120787924eed13455de3062523539dc39bc7f8
So should we use 1.0.0 in LLVM to remain consistency?

**Comment by NandniJamnadas** [comment]
@realqhc I have implemented the CORE-V extension in CORE-V Binutils-gdb and GCC as 1.0.0.

**Comment by jeremybennett** [comment]
@realqhc 1.3.1 is the version of the CV32E40P specification, of which the ISA extensions are just a small part.

For the ISA extensions, there is no versioning, as specified in [CORE-V ISA Naming](https://github.com/openhwgroup/core-v-sw/blob/master/specifications/corev-isa-extension-naming.md).  In accordance with the RISC-V specification, this means the ISA extension version is 1.0.0 as described by @NandniJamnadas
