### ISSUE TITLE
Update naming for xcvmem instructions

### ISSUE THREAD

**Issue by MaryBennett** [openhwgroup/corev-llvm-project#71]
Same as issues https://github.com/openhwgroup/corev-binutils-gdb/issues/101 and https://github.com/openhwgroup/corev-gcc/issues/60

Please update the post-inc xcvmem instructions to match the agreed spec.

Post-* cv.lw rd, (rs1), +/-imm/rs2

**Comment by jeremybennett** [comment]
Thank you for fixing this @ChunyuLiao
