### ISSUE TITLE
CORE-V C API Specification

### ISSUE THREAD

**Issue by simonpcook** [openhwgroup/corev-llvm-project#74]
Is this defined? See the comment at https://reviews.llvm.org/D157510#4573494

**Comment by ChunyuLiao** [comment]
Some information
Zb* and Zk* standard extenions :  https://github.com/riscv-non-isa/riscv-c-api-doc/pull/44
the implement: https://reviews.llvm.org/D155647

**Comment by melonedo** [comment]
See also https://github.com/openhwgroup/corev-gcc/issues/48

**Comment by PaoloS02** [comment]
The C API headers are now implemented.
