### ISSUE TITLE
How to check COREV_CLUSTER for Event Load Instruction

### ISSUE THREAD

**Issue by ChunyuLiao** [openhwgroup/corev-llvm-project#76]
Event Load Instruction
The event load instruction cv.elw is only supported if the COREV_CLUSTER parameter is set to 1. 

But how does the compiler detect the COREV_CLUSTER parameter.
or
The compiler does not require special checking and the user controls whether this extension is enabled or not？

ref:
https://github.com/openhwgroup/cv32e40p/blob/master/docs/source/instruction_set_extensions.rst#event-load-instruction

**Comment by jeremybennett** [comment]
I don't think the compiler has to worry about this.  If you ask for `xcvelw`, the compiler will provide the builtin and assembly instruction support. It is the user's responsibility to only run it on hardware which supports this extension.
